25/02/2022 05:26:01-INFO-simpleSock.py-61 l2_socket established
25/02/2022 05:26:01-WARNING-simpleSock.py-89 True
25/02/2022 05:26:45-WARNING-simpleSock.py-107 63
25/02/2022 05:26:45-WARNING-simpleSock.py-108 ['', '01', '08', '09', '16', '23', '30']
25/02/2022 05:26:45-WARNING-simpleSock.py-109 0:00:00.276296
25/02/2022 05:26:48-WARNING-simpleSock.py-107 66
25/02/2022 05:26:48-WARNING-simpleSock.py-108 ['', '01', '07', '14', '15', '22', '28', '35']
25/02/2022 05:26:48-WARNING-simpleSock.py-109 0:00:00.424992
25/02/2022 05:26:52-WARNING-simpleSock.py-107 69
25/02/2022 05:26:52-WARNING-simpleSock.py-108 ['', '01', '02', '03', '10', '11', '18', '23', '29']
25/02/2022 05:26:52-WARNING-simpleSock.py-109 0:00:00.311588
25/02/2022 05:26:53-WARNING-simpleSock.py-107 60
25/02/2022 05:26:53-WARNING-simpleSock.py-108 ['', '01', '08', '15', '22', '29']
25/02/2022 05:26:53-WARNING-simpleSock.py-109 0:00:00.328556
Traceback (most recent call last):
  File "/home/wifi/Downloads/simple/Idea-validation-ip-ccn/simpleSock.py", line 94, in <module>
    _rcvPkt = l2_sock.recv(123)
OSError: [Errno 100] Network is down
