25/02/2022 05:22:38-INFO-simpleSock.py-61 l2_socket established
25/02/2022 05:22:38-WARNING-simpleSock.py-89 True
Traceback (most recent call last):
  File "/home/wifi/Downloads/simple/Idea-validation-ip-ccn/simpleSock.py", line 94, in <module>
    _rcvPkt = l2_sock.recv(123)
OSError: [Errno 100] Network is down
